export const GET_DETAIL_ROOM_FETCH = "GET_DETAIL_ROOM_FETCH";
export const GET_DETAIL_ROOM_SUCCESS = "GET_DETAIL_ROOM_SUCCESS";

export const GET_DELETE_ROOM_FETCH = "GET_DELETE_ROOM_FETCH";
export const GET_DELETE_ROOM_SUCCESS = "GET_DELETE_ROOM_SUCCESS";

export const POST_CHOOSE_CLASS_FETCH = "POST_CHOOSE_CLASS_FETCH";
export const POST_CHOOSE_CLASS_SUCCESS = "POST_CHOOSE_CLASS_SUCCESS";
