export const PUT_FORM_FETCH = "PUT_FORM_FETCH";
export const PUT_FORM_SUCCESS = "PUT_FORM_SUCCESS";

export const GET_TOPICS_FETCH = "GET_TOPICS_FETCH";
export const GET_TOPICS_SUCCESS = "GET_TOPICS_SUCCESS";

export const GET_DETAIL_ROOM_FETCH = "GET_DETAIL_ROOM_FETCH";
export const GET_DETAIL_ROOM_SUCCESS = "GET_DETAIL_ROOM_SUCCESS";
