export const POST_FORM_FETCH = "POST_FORM_FETCH";
export const POST_FORM_SUCCESS = "POST_FORM_SUCCESS";

export const GET_TOPICS_FETCH = "GET_TOPICS_FETCH";
export const GET_TOPICS_SUCCESS = "GET_TOPICS_SUCCESS";
