export const GET_HOME_ROOMS_FETCH = "GET_HOME_ROOM_FETCH";
export const GET_HOME_ROOMS_SUCCESS = "GET_HOME_ROOM_SUCCESS";

export const GET_HOME_TOPICS_FETCH = "GET_TOPICS_FETCH";
export const GET_HOME_TOPICS_SUCCESS = "GET_TOPICS_SUCCESS";
