export const GET_CREATED_ROOM_FETCH = "GET_CREATED_ROOM_FETCH";
export const GET_CREATED_ROOM_SUCCESS = "GET_CREATED_ROOM_SUCCESS";

export const GET_JOINED_ROOM_FETCH = "GET_JOINED_ROOM_FETCH";
export const GET_JOINED_ROOM_SUCCESS = "GET_JOINED_ROOM_SUCCESS";
