export const GET_ROOMS_FETCH = "GET_ROOM_FETCH";
export const GET_ROOMS_SUCCESS = "GET_ROOM_SUCCESS";

export const GET_TOPICS_FETCH = "GET_TOPICS_FETCH";
export const GET_TOPICS_SUCCESS = "GET_TOPICS_SUCCESS";
